<?php
return array(
	//'配置项'=>'配置值'
	'name'=>'xuetu',
	'URL_MODEL'=>2,
	//伪静态后缀设置
	'URL_HTML_SUFFIX'=>'shtml|html|xml',
	//数据库类型
	'DB_TYPE'=>'mysql',
	//数据库IP
	'DB_HOST'=>'127.0.0.1',
	//数据库用户名
	'DB_USER'=>'root',
	//数据库密码
	'DB_PWD'=>'666666',
	//数据库名
	'DB_NAME'=>'test',
	//数据库端口号
	'DB_PORT'=>'3306',
	//数据库前缀
	'DB_PREFIX'=>'',
);
?>